# Mosquitto MQTT Broker Configuration
# Tanpa autentikasi — untuk development/lokal

listener 1883
allow_anonymous true

# Logging
log_type error
log_type warning
log_type notice
log_type information

# Persistence (opsional — simpan pesan saat broker restart)
persistence true
persistence_location /mosquitto/data/

log_dest stdout
